## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [2]:
org_movies = pd.read_csv('IMDB_Movies.csv')
movies = org_movies
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [3]:
movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [4]:
movies.iloc[3510]

color                                                                    Color
director_name                                                      Yash Chopra
num_critic_for_reviews                                                    29.0
duration                                                                 192.0
director_facebook_likes                                                  147.0
actor_3_facebook_likes                                                   397.0
actor_2_name                                                      Preity Zinta
actor_1_facebook_likes                                                  8000.0
gross                                                                2921738.0
genres                                                   Drama|Musical|Romance
actor_1_name                                                    Shah Rukh Khan
movie_title                                                        Veer-Zaara
num_voted_users                                                          34449
cast_total_facebook_likes                                                 9984
actor_3_name                                                       Anupam Kher
facenumber_in_poster                                                       0.0
plot_keywords                             fair|pakistan|prison|rescue|stranded
movie_imdb_link              http://www.imdb.com/title/tt0420332/?ref_=fn_t...
num_user_for_reviews                                                       119
language                                                                 Hindi
country                                                                  India
content_rating                                                             NaN
budget                                                               7000000.0
title_year                                                              2004.0
actor_2_facebook_likes                                                   860.0
imdb_score                                                                 7.9
aspect_ratio                                                              2.35
movie_facebook_likes                                                      2000
Name: 3510, dtype: object

In [5]:
movies.shape

(5043, 28)

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5023 non-null   object
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(12), int64(3), object(13)
memory usage: 1.1+ MB

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [7]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          20
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

# Write your code for row-wise null count here

In [8]:
movies.isnull().sum(axis = 1)

0        0
1        0
2        0
3        0
4       13
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [9]:
# Write your code for column-wise null percentages here
null_percent = movies.isnull().sum()/len(movies)*100
null_percent

color                         0.376760
director_name                 2.062265
num_critic_for_reviews        0.991473
duration                      0.297442
director_facebook_likes       2.062265
actor_3_facebook_likes        0.456078
actor_2_name                  0.257783
actor_1_facebook_likes        0.138806
gross                        17.529248
genres                        0.000000
actor_1_name                  0.138806
movie_title                   0.000000
num_voted_users               0.000000
cast_total_facebook_likes     0.000000
actor_3_name                  0.456078
facenumber_in_poster          0.257783
plot_keywords                 3.033908
movie_imdb_link               0.000000
num_user_for_reviews          0.396589
language                      0.277613
country                       0.099147
content_rating                6.008328
budget                        9.756098
title_year                    2.141582
actor_2_facebook_likes        0.257783
imdb_score                    0.000000
aspect_ratio                  6.523895
movie_facebook_likes          0.000000
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [10]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of opera
movies.drop(['color',
'director_facebook_likes',
'actor_1_facebook_likes',
'actor_2_facebook_likes',
'actor_3_facebook_likes',
'actor_2_name',
'cast_total_facebook_likes',
'actor_3_name',
'duration',
'facenumber_in_poster',
'content_rating',
'country',
'movie_imdb_link',
'aspect_ratio',
'plot_keywords'], axis = 1, inplace = True)

In [11]:
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [12]:
# Write your code for column-wise null percentages here
null_percent = movies.isnull().sum()/len(movies)*100       #writing it again so that null_percent gets updated after droping unnecessary columns
null_percent

# Write your code for dropping the rows here
null_percent.sort_values(ascending = False)

gross                     17.529248
budget                     9.756098
title_year                 2.141582
director_name              2.062265
num_critic_for_reviews     0.991473
num_user_for_reviews       0.396589
language                   0.277613
actor_1_name               0.138806
genres                     0.000000
movie_title                0.000000
num_voted_users            0.000000
imdb_score                 0.000000
movie_facebook_likes       0.000000
dtype: float64

In [13]:
movies_cleaned = movies.dropna(subset = null_percent[null_percent>5].index)
movies_cleaned

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84,English,1100.0,2004.0,6.6,456

In [14]:
movies_cleaned.isnull().sum().sort_values(ascending = False)

language                  4
actor_1_name              3
num_critic_for_reviews    1
director_name             0
gross                     0
genres                    0
movie_title               0
num_voted_users           0
num_user_for_reviews      0
budget                    0
title_year                0
imdb_score                0
movie_facebook_likes      0
dtype: int64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [15]:
# Write your code for dropping the rows here

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [16]:
# Write your code here
# movies_cleaned['language'].unique()
# movies_cleaned['language'].nunique()
movies_cleaned['language'].value_counts()

language
English       3707
French          37
Spanish         26
Mandarin        15
German          13
Japanese        12
Hindi           10
Cantonese        8
Italian          7
Portuguese       5
Korean           5
Norwegian        4
Thai             3
Hebrew           3
Persian          3
Danish           3
Dutch            3
Dari             2
Indonesian       2
Aboriginal       2
Arabic           1
Russian          1
Vietnamese       1
Dzongkha         1
Romanian         1
Zulu             1
Bosnian          1
Czech            1
Icelandic        1
Hungarian        1
Mongolian        1
Aramaic          1
Telugu           1
Kazakh           1
Maya             1
Filipino         1
Swedish          1
Name: count, dtype: int64

In [17]:
movies_cleaned['language'].fillna('English', inplace = True)
movies_cleaned.isnull().sum()

C:\Users\sony\AppData\Local\Temp\ipykernel_5692\189964088.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies_cleaned['language'].fillna('English', inplace = True)
C:\Users\sony\AppData\Local\Temp\ipykernel_5692\189964088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_cleaned['language'].fillna('English', inplace = True)

director_name             0
num_critic_for_reviews    1
gross                     0
genres                    0
actor_1_name              3
movie_title               0
num_voted_users           0
num_user_for_reviews      0
language                  0
budget                    0
title_year                0
imdb_score                0
movie_facebook_likes      0
dtype: int64

In [18]:
movies_cleaned['language'].value_counts()

language
English       3711
French          37
Spanish         26
Mandarin        15
German          13
Japanese        12
Hindi           10
Cantonese        8
Italian          7
Portuguese       5
Korean           5
Norwegian        4
Thai             3
Hebrew           3
Persian          3
Danish           3
Dutch            3
Dari             2
Indonesian       2
Aboriginal       2
Arabic           1
Russian          1
Vietnamese       1
Dzongkha         1
Romanian         1
Zulu             1
Bosnian          1
Czech            1
Icelandic        1
Hungarian        1
Mongolian        1
Aramaic          1
Telugu           1
Kazakh           1
Maya             1
Filipino         1
Swedish          1
Name: count, dtype: int64

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [19]:
# Write your code for checking number of retained rows here
movies_cleaned.shape
retained_percent = (movies_cleaned.shape[0]/org_movies.shape[0])*100
retained_percent

77.15645449137418

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis
-  ### Subtask 3.1: Change the unit of columns
Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [20]:
# Write your code for unit conversion here
movies_cleaned.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738,English,263700000.0,2012.0,6.6,24000

In [21]:
movies_cleaned['gross']/=1000000
movies_cleaned

C:\Users\sony\AppData\Local\Temp\ipykernel_5692\495881052.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_cleaned['gross']/=1000000

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84,English,1100.0,2004.0,6.6,456

In [22]:
movies_cleaned['budget']/=1000000
movies_cleaned

C:\Users\sony\AppData\Local\Temp\ipykernel_5692\4285170619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_cleaned['budget']/=1000000

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0000,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300.0000,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245.0000,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250.0000,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738,English,263.7000,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371,English,0.0070,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35,English,0.0070,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130,Spanish,0.0070,1992.0,6.9,0
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14,English,0.0090,2011.0,6.4,413
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84,English,0.0011,2004.0,6.6,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [23]:
# Write your code for creating the profit column here
movies_cleaned['profit'] = movies_cleaned['gross'] - movies_cleaned['budget']
movies_cleaned

C:\Users\sony\AppData\Local\Temp\ipykernel_5692\1928123122.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_cleaned['profit'] = movies_cleaned['gross'] - movies_cleaned['budget']

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0000,2009.0,7.9,33000,523.505847
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300.0000,2007.0,7.1,0,9.404152
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245.0000,2015.0,6.8,85000,-44.925825
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250.0000,2012.0,8.5,164000,198.130642
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738,English,263.7000,2012.0,6.6,24000,-190.641321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371,English,0.0070,2004.0,7.0,19000,0.417760
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35,English,0.0070,2005.0,6.3,74,0.063071
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130,Spanish,0.0070,1992.0,6.9,0,2.033920
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14,English,0.0090,2011.0,6.4,413,-0.004416
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84,English,0.0011,2004.0,6.6,456,0.084122

In [24]:
# Write your code for sorting the dataframe here
movies_cleaned = movies_cleaned.sort_values(['profit'], ascending = False)
movies_cleaned
#OR
# movies_cleaned.sort_values(['profit'], ascending = False, inplace = True)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [25]:
# Write your code for top10 movies
movies_cleaned.head(10)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,185.0,2008.0,9.0,37000,348.316061

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [26]:
# Write your code for dropping duplicate values here
movies_cleaned = movies_cleaned.drop_duplicates()
movies_cleaned

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [27]:
# Write code for repeating subtask 2 here
movies_cleaned.head(10)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,185.0,2008.0,9.0,37000,348.316061
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959,English,78.0,2012.0,7.3,140000,329.999255

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [28]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe
# and name that dataframe as 'IMDb_Top_250'
movies_cleaned = movies_cleaned.sort_values(['imdb_score'], ascending = False)
movies_cleaned

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144,English,25.0,1994.0,9.3,108000,3.341469
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238,English,6.0,1972.0,9.2,43000,128.821952
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,185.0,2008.0,9.0,37000,348.316061
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650,English,13.0,1974.0,9.0,14000,44.300000
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189,English,94.0,2003.0,8.9,16000,283.019252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3664,Preston A. Whitmore II,25.0,7.009668,Action|Sport,Wesley Jonathan,Crossover,8707,36,English,5.6,2006.0,2.1,244,1.409668
3505,Don Michael Paul,25.0,5.694308,Comedy|Sport,Jeffrey Jones,Who's Your Caddy?,13815,46,English,7.0,2007.0,2.0,446,-1.305692
2268,Jason Friedberg,111.0,14.174654,Comedy,Carmen Electra,Disaster Movie,74945,359,English,25.0,2008.0,1.9,0,-10.825346
2295,Bob Clark,32.0,9.109322,Comedy|Family|Sci-Fi,Scott Baio,Superbabies: Baby Geniuses 2,25371,129,English,20.0,2004.0,1.9,0,-10.890678
2834,Jon M. Chu,84.0,73.000942,Documentary|Music,Usher Raymond,Justin Bieber: Never Say Never,74351,233,English,13.0,2011.0,1.6,62000,60.000942

In [29]:
filtered_movies = movies_cleaned[movies_cleaned['num_voted_users']>25000]
IMDb_Top_250 = filtered_movies.sort_values(['imdb_score'], ascending = False)
IMDb_Top_250['Rank'] = IMDb_Top_250['imdb_score'].rank(method = 'first', ascending = False)
IMDb_Top_250.head(250)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144,English,25.0,1994.0,9.3,108000,3.341469,1.0
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238,English,6.0,1972.0,9.2,43000,128.821952,2.0
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,185.0,2008.0,9.0,37000,348.316061,3.0
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650,English,13.0,1974.0,9.0,14000,44.300000,4.0
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189,English,94.0,2003.0,8.9,16000,283.019252,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452,Paul Haggis,287.0,54.557348,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624,English,6.5,2004.0,7.9,18000,48.057348,246.0
3680,Spike Lee,103.0,27.545445,Drama,Ruby Dee,Do the Right Thing,59524,418,English,6.5,1989.0,7.9,0,21.045445,247.0
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119,Hindi,7.0,2004.0,7.9,2000,-4.078262,248.0
2449,Tim Burton,148.0,5.887457,Biography|Comedy|Drama,Johnny Depp,Ed Wood,142416,420,English,18.0,1994.0,7.9,0,-12.112543,249.0
845,Paul Greengrass,491.0,107.100855,Biography|Drama|Thriller,Tom Hanks,Captain Phillips,323353,527,English,55.0,2013.0,7.9,65000,52.100855,250.0

In [30]:
Top_Foreign_Lang_Film = movies_cleaned[movies_cleaned['language']!='English']
Top_Foreign_Lang_Film = Top_Foreign_Lang_Film.sort_values(['imdb_score'], ascending = False)
Top_Foreign_Lang_Film['Rank'] = Top_Foreign_Lang_Film['imdb_score'].rank(method = 'first', ascending = False)
Top_Foreign_Lang_Film.head(250)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780,Italian,1.2,1966.0,8.9,20000,4.900000,1.0
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596,Japanese,2.0,1954.0,8.7,11000,-1.730939,2.0
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749,Portuguese,3.3,2002.0,8.7,28000,4.263397,3.0
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902,Japanese,19.0,2001.0,8.6,28000,-8.950114,4.0
4259,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407,German,2.0,2006.0,8.5,39000,9.284657,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3455,Siddharth Anand,16.0,0.872643,Comedy|Family|Romance,Saif Ali Khan,Ta Ra Rum Pum,2909,37,Hindi,6.0,2007.0,5.4,108,-5.127357,175.0
1957,Steve Barron,19.0,15.091542,Adventure|Family|Fantasy|Musical,Martin Landau,The Adventures of Pinocchio,4086,22,Italian,25.0,1996.0,5.3,246,-9.908458,176.0
3731,Bille Woodruff,9.0,17.382982,Drama|Thriller,Boris Kodjoe,Addicted,5975,33,Spanish,5.0,2014.0,5.2,0,12.382982,177.0
4593,Vivek Agnihotri,4.0,0.049000,Thriller,Emraan Hashmi,Chocolate: Deep Dark Secrets,1524,30,Hindi,1.5,2005.0,4.8,31,-1.451000,178.0
2890,Angelina Jolie Pitt,110.0,0.301305,Drama|Romance|War,Jelena Jovanova,In the Land of Blood and Honey,31414,180,Bosnian,13.0,2011.0,4.3,0,-12.698695,179.0

In [31]:
Top_Foreign_Lang_Film[Top_Foreign_Lang_Film['movie_title'].str.strip()=='Veer-Zaara']

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119,Hindi,7.0,2004.0,7.9,2000,-4.078262,38.0

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [32]:
# Write your code for extracting the top 10 directors here
top10director = movies_cleaned.groupby('director_name')['imdb_score'].mean()
top10director.sort_values(ascending = False, inplace = True)
top10director.head(10)

director_name
Charles Chaplin          8.600000
Tony Kaye                8.600000
Alfred Hitchcock         8.500000
Ron Fricke               8.500000
Damien Chazelle          8.500000
Majid Majidi             8.500000
Sergio Leone             8.433333
Christopher Nolan        8.425000
S.S. Rajamouli           8.400000
Marius A. Markevicius    8.400000
Name: imdb_score, dtype: float64

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [33]:
movies_cleaned[['genre_1', 'genre_2']] = movies_cleaned['genres'].str.split('|',n=1, expand = True)
movies_cleaned['genre_2'] = movies_cleaned['genre_2'].str.split('|').str[0]
movies_cleaned

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144,English,25.0,1994.0,9.3,108000,3.341469,Crime,Drama
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238,English,6.0,1972.0,9.2,43000,128.821952,Crime,Drama
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,185.0,2008.0,9.0,37000,348.316061,Action,Crime
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650,English,13.0,1974.0,9.0,14000,44.300000,Crime,Drama
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189,English,94.0,2003.0,8.9,16000,283.019252,Action,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3664,Preston A. Whitmore II,25.0,7.009668,Action|Sport,Wesley Jonathan,Crossover,8707,36,English,5.6,2006.0,2.1,244,1.409668,Action,Sport
3505,Don Michael Paul,25.0,5.694308,Comedy|Sport,Jeffrey Jones,Who's Your Caddy?,13815,46,English,7.0,2007.0,2.0,446,-1.305692,Comedy,Sport
2268,Jason Friedberg,111.0,14.174654,Comedy,Carmen Electra,Disaster Movie,74945,359,English,25.0,2008.0,1.9,0,-10.825346,Comedy,None
2295,Bob Clark,32.0,9.109322,Comedy|Family|Sci-Fi,Scott Baio,Superbabies: Baby Geniuses 2,25371,129,English,20.0,2004.0,1.9,0,-10.890678,Comedy,Family
2834,Jon M. Chu,84.0,73.000942,Documentary|Music,Usher Raymond,Justin Bieber: Never Say Never,74351,233,English,13.0,2011.0,1.6,62000,60.000942,Documentary,Music

In [34]:
movies_cleaned['genre_2'] = movies_cleaned['genre_2'].fillna(movies_cleaned['genre_1'])
movies_cleaned

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144,English,25.0,1994.0,9.3,108000,3.341469,Crime,Drama
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238,English,6.0,1972.0,9.2,43000,128.821952,Crime,Drama
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,185.0,2008.0,9.0,37000,348.316061,Action,Crime
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650,English,13.0,1974.0,9.0,14000,44.300000,Crime,Drama
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189,English,94.0,2003.0,8.9,16000,283.019252,Action,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3664,Preston A. Whitmore II,25.0,7.009668,Action|Sport,Wesley Jonathan,Crossover,8707,36,English,5.6,2006.0,2.1,244,1.409668,Action,Sport
3505,Don Michael Paul,25.0,5.694308,Comedy|Sport,Jeffrey Jones,Who's Your Caddy?,13815,46,English,7.0,2007.0,2.0,446,-1.305692,Comedy,Sport
2268,Jason Friedberg,111.0,14.174654,Comedy,Carmen Electra,Disaster Movie,74945,359,English,25.0,2008.0,1.9,0,-10.825346,Comedy,Comedy
2295,Bob Clark,32.0,9.109322,Comedy|Family|Sci-Fi,Scott Baio,Superbabies: Baby Geniuses 2,25371,129,English,20.0,2004.0,1.9,0,-10.890678,Comedy,Family
2834,Jon M. Chu,84.0,73.000942,Documentary|Music,Usher Raymond,Justin Bieber: Never Say Never,74351,233,English,13.0,2011.0,1.6,62000,60.000942,Documentary,Music

In [35]:
grouped = movies_cleaned.groupby(['genre_1', 'genre_2'])['gross'].mean()
grouped.sort_values(ascending = False, inplace = True)
grouped.head(5)

genre_1    genre_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
           Family       118.919540
           Animation    116.998550
Action     Adventure    109.595465
Name: gross, dtype: float64

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [36]:
# Write your code for creating three new dataframes here
Meryl_Streep = movies_cleaned[movies_cleaned['actor_1_name'] == 'Meryl Streep']
Meryl_Streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123,660,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283,112,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller

In [37]:
Leo_Caprio = movies_cleaned[movies_cleaned['actor_1_name'] == 'Leonardo DiCaprio']
Leo_Caprio

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
361,Martin Scorsese,352.0,132.373442,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
308,Martin Scorsese,606.0,116.866727,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
452,Martin Scorsese,490.0,127.968405,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
179,Alejandro G. Iñárritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
307,Edward Zwick,166.0,57.366262,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
326,Martin Scorsese,233.0,77.679638,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
257,Martin Scorsese,267.0,102.608827,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
1114,Sam Mendes,323.0,22.877808,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
50,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
3476,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
641,Ridley Scott,238.0,39.380442,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
2757,Baz Luhrmann,106.0,46.338728,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
2067,Jerry Zaks,45.0,12.782508,Drama,Leonardo DiCaprio,Marvin's Room,20163,71,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
1453,Clint Eastwood,392.0,37.304950,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
990,Danny Boyle,118.0,39.778599,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1560,Sam Raimi,63.0,18.636537,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
1422,Randall Wallace,83.0,56.876365,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure

In [38]:
Brad_Pitt = movies_cleaned[movies_cleaned['actor_1_name'] == 'Brad Pitt']
Brad_Pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
2898,Tony Scott,122.0,12.281500,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
101,David Fincher,362.0,127.490802,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
1722,Andrew Dominik,273.0,3.904982,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,34.300771,Drama,Brad Pitt,Babel,243799,908,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
147,Wolfgang Petersen,220.0,133.228348,Adventure,Brad Pitt,Troy,381672,1694,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
382,Tony Scott,142.0,0.026871,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime
611,Jean-Jacques Annaud,76.0,37.901509,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
792,Patrick Gilmore,98.0,26.288320,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
1490,Terrence Malick,584.0,13.303319,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
2682,Andrew Dominik,414.0,14.938570,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2333,Angelina Jolie Pitt,131.0,0.531009,Drama|Romance,Brad Pitt,By the Sea,7976,61,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance

In [39]:
Combined = pd.concat([Meryl_Streep,Leo_Caprio,Brad_Pitt])
Combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123,660,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283,112,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
361,Martin Scorsese,352.0,132.373442,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
308,Martin Scorsese,606.0,116.866727,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
452,Martin Scorsese,490.0,127.968405,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
179,Alejandro G. Iñárritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
307,Edward Zwick,166.0,57.366262,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
326,Martin Scorsese,233.0,77.679638,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
257,Martin Scorsese,267.0,102.608827,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
1114,Sam Mendes,323.0,22.877808,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
50,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
3476,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
641,Ridley Scott,238.0,39.380442,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
2757,Baz Luhrmann,106.0,46.338728,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
2067,Jerry Zaks,45.0,12.782508,Drama,Leonardo DiCaprio,Marvin's Room,20163,71,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
1453,Clint Eastwood,392.0,37.304950,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
990,Danny Boyle,118.0,39.778599,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1560,Sam Raimi,63.0,18.636537,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
1422,Randall Wallace,83.0,56.876365,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
2898,Tony Scott,122.0,12.281500,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
101,David Fincher,362.0,127.490802,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
1722,Andrew Dominik,273.0,3.904982,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
2204,Alejandro G. Iñárritu,285.0,34.300771,Drama,Brad Pitt,Babel,243799,908,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
147,Wolfgang Petersen,220.0,133.228348,Adventure,Brad Pitt,Troy,381672,1694,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
382,Tony Scott,142.0,0.026871,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime
611,Jean-Jacques Annaud,76.0,37.901509,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
792,Patrick Gilmore,98.0,26.288320,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
1490,Terrence Malick,584.0,13.303319,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
2682,Andrew Dominik,414.0,14.938570,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2333,Angelina Jolie Pitt,131.0,0.531009,Drama|Romance,Brad Pitt,By the Sea,7976,61,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance

In [48]:
#Strip whitespace and convert to numeric
Combined['num_user_for_reviews'] = pd.to_numeric(Combined['num_user_for_reviews'].str.strip(), errors='coerce')

In [49]:
Combined.groupby('actor_1_name')['num_critic_for_reviews'].mean()

actor_1_name
Brad Pitt            245.000000
Leonardo DiCaprio    330.190476
Meryl Streep         181.454545
Name: num_critic_for_reviews, dtype: float64

In [50]:
Combined.groupby('actor_1_name')['num_user_for_reviews'].mean()

actor_1_name
Brad Pitt            742.352941
Leonardo DiCaprio    914.476190
Meryl Streep         297.181818
Name: num_user_for_reviews, dtype: float64

**Checkpoint 6:** `Leonardo` has aced both the lists!